export const employeeListResponse = {
  data: [
    {
      id: 1,
      employeeId: "EMP-001",
      name: "Ajay Shakya",
      email: "ajay@elmechindia.com",
      phone: "9876543210",
      designation: "Software Engineer",
      department: "IT",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 2,
      employeeId: "EMP-002",
      name: "Rohit Mehra",
      email: "rohit@elmechindia.com",
      phone: "9123456789",
      designation: "Civil Engineer",
      department: "Civil",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 3,
      employeeId: "EMP-003",
      name: "Amit Verma",
      email: "amit@elmechindia.com",
      phone: "9988776655",
      designation: "Electrical Engineer",
      department: "Electrical",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 4,
      employeeId: "EMP-004",
      name: "Sandeep Singh",
      email: "sandeep@elmechindia.com",
      phone: "9012345678",
      designation: "Fire Fighting Engineer",
      department: "Fire Fighting",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 5,
      employeeId: "EMP-005",
      name: "Neha Sharma",
      email: "neha@elmechindia.com",
      phone: "9090909090",
      designation: "HR Executive",
      department: "HR",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 6,
      employeeId: "EMP-006",
      name: "Vikas Yadav",
      email: "vikas@elmechindia.com",
      phone: "9811223344",
      designation: "Site Supervisor",
      department: "Site",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 7,
      employeeId: "EMP-007",
      name: "Pankaj Kumar",
      email: "pankaj@elmechindia.com",
      phone: "9822334455",
      designation: "Project Manager",
      department: "Management",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 8,
      employeeId: "EMP-008",
      name: "Sunita Gupta",
      email: "sunita@elmechindia.com",
      phone: "9877001122",
      designation: "Accounts Manager",
      department: "Accounts",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 9,
      employeeId: "EMP-009",
      name: "Ravi Chauhan",
      email: "ravi@elmechindia.com",
      phone: "9898989898",
      designation: "Mechanical Engineer",
      department: "Mechanical",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 10,
      employeeId: "EMP-010",
      name: "Deepak Mishra",
      email: "deepak@elmechindia.com",
      phone: "9700011122",
      designation: "Store Manager",
      department: "Store",
      workingStatus: "resigned",
      organization: "ElMech India Engineers",
    },
    {
      id: 11,
      employeeId: "EMP-011",
      name: "Manish Tiwari",
      email: "manish@elmechindia.com",
      phone: "9998887776",
      designation: "Safety Officer",
      department: "Safety",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 12,
      employeeId: "EMP-012",
      name: "Anjali Jain",
      email: "anjali@elmechindia.com",
      phone: "9112233445",
      designation: "Architect",
      department: "Design",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 13,
      employeeId: "EMP-013",
      name: "Kunal Saxena",
      email: "kunal@elmechindia.com",
      phone: "9333444555",
      designation: "Planning Engineer",
      department: "Planning",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 14,
      employeeId: "EMP-014",
      name: "Rahul Malhotra",
      email: "rahul@elmechindia.com",
      phone: "9444555666",
      designation: "QA/QC Engineer",
      department: "Quality",
      workingStatus: "terminated",
      organization: "ElMech India Engineers",
    },
    {
      id: 15,
      employeeId: "EMP-015",
      name: "Shubham Agarwal",
      email: "shubham@elmechindia.com",
      phone: "9555666777",
      designation: "Procurement Officer",
      department: "Procurement",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
  ],
  meta: {
    total: 15,
    limit: 10,
    offset: 0,
    hasNextPage: true,
  },
};
export const salaryManagementResponse = {
  data: [
    {
      id: 1,
      employeeId: "EMP-001",
      name: "Ajay Shakya",
      department: "IT",
      designation: "Software Engineer",
      currentSalary: 65000,
      salaryHistory: [
        { from: "2023-01", to: "2023-06", salary: 45000 },
        { from: "2023-07", to: "2024-02", salary: 55000 },
        { from: "2024-03", to: "Present", salary: 65000, isActive: true },
      ],
    },
    {
      id: 2,
      employeeId: "EMP-002",
      name: "Rohit Mehra",
      department: "Civil",
      designation: "Civil Engineer",
      currentSalary: 72000,
      salaryHistory: [
        { from: "2022-04", to: "2023-03", salary: 50000 },
        { from: "2023-04", to: "Present", salary: 72000, isActive: true },
      ],
    },
    {
      id: 3,
      employeeId: "EMP-003",
      name: "Amit Verma",
      department: "Electrical",
      designation: "Electrical Engineer",
      currentSalary: 68000,
      salaryHistory: [
        { from: "2022-01", to: "2022-12", salary: 42000 },
        { from: "2023-01", to: "2023-12", salary: 58000 },
        { from: "2024-01", to: "Present", salary: 68000, isActive: true },
      ],
    },
    {
      id: 4,
      employeeId: "EMP-004",
      name: "Sandeep Singh",
      department: "Fire Fighting",
      designation: "Fire Safety Engineer",
      currentSalary: 60000,
      salaryHistory: [
        { from: "2023-01", to: "Present", salary: 60000, isActive: true },
      ],
    },
  ],
  meta: {
    total: 4,
    currency: "INR",
  },
};

export const queryListResponse = {
  data: [
    {
      id: "QRY-001",
      userId: "USR-101",
      userName: "Ajay Shakya",
      email: "ajay@example.com",
      subject: "Login issue",
      description: "Unable to login after password reset",
      priority: "high", 
      status: "pending", 
      createdAt: "2024-12-01",
    },
    {
      id: "QRY-002",
      userId: "USR-102",
      userName: "Rohit Mehra",
      email: "rohit@example.com",
      subject: "Salary slip not generated",
      description: "Salary slip for November is missing",
      priority: "medium",
      status: "resolved",
      createdAt: "2024-12-03",
    },
    {
      id: "QRY-003",
      userId: "USR-103",
      userName: "Amit Verma",
      email: "amit@example.com",
      subject: "Project access",
      description: "Unable to access assigned project",
      priority: "high",
      status: "pending",
      createdAt: "2024-12-05",
    },
    {
      id: "QRY-004",
      userId: "USR-104",
      userName: "Neha Sharma",
      email: "neha@example.com",
      subject: "Profile update issue",
      description: "Changes not saving in profile",
      priority: "low",
      status: "resolved",
      createdAt: "2024-12-06",
    },
    {
      id: "QRY-005",
      userId: "USR-105",
      userName: "Sandeep Singh",
      email: "sandeep@example.com",
      subject: "Site allocation",
      description: "Site location not updated",
      priority: "medium",
      status: "pending",
      createdAt: "2024-12-08",
    },
  ],
  meta: {
    total: 5,
    openQueries: 3,
    resolvedQueries: 2,
  },
};

export const commentListResponse = {
  data: [
    {
      id: "CMT-001",
      userId: "USR-101",
      userName: "Ajay Shakya",
      comment: "The new dashboard UI looks very clean and modern.",
      rating: 5,
      isApproved: true,
      createdAt: "2024-12-02",
    },
    {
      id: "CMT-002",
      userId: "USR-102",
      userName: "Rohit Mehra",
      comment: "Salary management feature is very helpful.",
      rating: 4,
      isApproved: true,
      createdAt: "2024-12-04",
    },
    {
      id: "CMT-003",
      userId: "USR-103",
      userName: "Amit Verma",
      comment: "Employee filter could be faster.",
      rating: 3,
      isApproved: false,
      createdAt: "2024-12-05",
    },
    {
      id: "CMT-004",
      userId: "USR-104",
      userName: "Neha Sharma",
      comment: "Project module is very easy to use.",
      rating: 5,
      isApproved: true,
      createdAt: "2024-12-07",
    },
    {
      id: "CMT-005",
      userId: "USR-105",
      userName: "Sandeep Singh",
      comment: "Need dark mode support.",
      rating: 4,
      isApproved: false,
      createdAt: "2024-12-09",
    },
  ],
  meta: {
    total: 5,
    approved: 3,
    pending: 2,
  },
};

export const allUsersResponse = {
  data: [
    {
      id: 1,
      employeeId: "EMP-001",
      name: "Ajay Shakya",
      role: "Admin",
      department: "IT",
      status: "active",
    },
    {
      id: 2,
      employeeId: "EMP-002",
      name: "Rohit Mehra",
      role: "Employee",
      department: "Civil",
      status: "active",
    },
    {
      id: 3,
      employeeId: "EMP-003",
      name: "Amit Verma",
      role: "Employee",
      department: "Electrical",
      status: "inactive",
    },
  ],
  meta: {
    total: 3,
  },
};

export const allProjectsResponse = {
  data: [
    {
      id: 1,
      projectCode: "PRJ-001",
      projectName: "IT Park Electrical Work",
      department: "Electrical",
      clientName: "TCS",
      status: "active",
    },
    {
      id: 2,
      projectCode: "PRJ-002",
      projectName: "Hospital Fire System",
      department: "Fire Fighting",
      clientName: "Apollo Hospitals",
      status: "completed",
    },
    {
      id: 3,
      projectCode: "PRJ-003",
      projectName: "Residential Tower Construction",
      department: "Civil",
      clientName: "DLF",
      status: "active",
    },
  ],
  meta: {
    total: 3,
  },
};
