export const employeeListResponse = {
  data: [
    {
      id: 1,
      employeeId: "EMP-001",
      name: "Ajay Shakya",
      email: "ajay@elmechindia.com",
      phone: "9876543210",
      designation: "Software Engineer",
      department: "IT",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 2,
      employeeId: "EMP-002",
      name: "Rohit Mehra",
      email: "rohit@elmechindia.com",
      phone: "9123456789",
      designation: "Civil Engineer",
      department: "Civil",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 3,
      employeeId: "EMP-003",
      name: "Amit Verma",
      email: "amit@elmechindia.com",
      phone: "9988776655",
      designation: "Electrical Engineer",
      department: "Electrical",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 4,
      employeeId: "EMP-004",
      name: "Sandeep Singh",
      email: "sandeep@elmechindia.com",
      phone: "9012345678",
      designation: "Fire Fighting Engineer",
      department: "Fire Fighting",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 5,
      employeeId: "EMP-005",
      name: "Neha Sharma",
      email: "neha@elmechindia.com",
      phone: "9090909090",
      designation: "HR Executive",
      department: "HR",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 6,
      employeeId: "EMP-006",
      name: "Vikas Yadav",
      email: "vikas@elmechindia.com",
      phone: "9811223344",
      designation: "Site Supervisor",
      department: "Site",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 7,
      employeeId: "EMP-007",
      name: "Pankaj Kumar",
      email: "pankaj@elmechindia.com",
      phone: "9822334455",
      designation: "Project Manager",
      department: "Management",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 8,
      employeeId: "EMP-008",
      name: "Sunita Gupta",
      email: "sunita@elmechindia.com",
      phone: "9877001122",
      designation: "Accounts Manager",
      department: "Accounts",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 9,
      employeeId: "EMP-009",
      name: "Ravi Chauhan",
      email: "ravi@elmechindia.com",
      phone: "9898989898",
      designation: "Mechanical Engineer",
      department: "Mechanical",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 10,
      employeeId: "EMP-010",
      name: "Deepak Mishra",
      email: "deepak@elmechindia.com",
      phone: "9700011122",
      designation: "Store Manager",
      department: "Store",
      workingStatus: "resigned",
      organization: "ElMech India Engineers",
    },
    {
      id: 11,
      employeeId: "EMP-011",
      name: "Manish Tiwari",
      email: "manish@elmechindia.com",
      phone: "9998887776",
      designation: "Safety Officer",
      department: "Safety",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 12,
      employeeId: "EMP-012",
      name: "Anjali Jain",
      email: "anjali@elmechindia.com",
      phone: "9112233445",
      designation: "Architect",
      department: "Design",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 13,
      employeeId: "EMP-013",
      name: "Kunal Saxena",
      email: "kunal@elmechindia.com",
      phone: "9333444555",
      designation: "Planning Engineer",
      department: "Planning",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
    {
      id: 14,
      employeeId: "EMP-014",
      name: "Rahul Malhotra",
      email: "rahul@elmechindia.com",
      phone: "9444555666",
      designation: "QA/QC Engineer",
      department: "Quality",
      workingStatus: "terminated",
      organization: "ElMech India Engineers",
    },
    {
      id: 15,
      employeeId: "EMP-015",
      name: "Shubham Agarwal",
      email: "shubham@elmechindia.com",
      phone: "9555666777",
      designation: "Procurement Officer",
      department: "Procurement",
      workingStatus: "working",
      organization: "ElMech India Engineers",
    },
  ],
  meta: {
    total: 15,
    limit: 10,
    offset: 0,
    hasNextPage: true,
  },
};
export const salaryManagementResponse = {
  data: [
    {
      id: 1,
      employeeId: "EMP-001",
      name: "Ajay Shakya",
      department: "IT",
      designation: "Software Engineer",
      currentSalary: 65000,
      salaryHistory: [
        { from: "2023-01", to: "2023-06", salary: 45000 },
        { from: "2023-07", to: "2024-02", salary: 55000 },
        { from: "2024-03", to: "Present", salary: 65000, isActive: true },
      ],
    },
    {
      id: 2,
      employeeId: "EMP-002",
      name: "Rohit Mehra",
      department: "Civil",
      designation: "Civil Engineer",
      currentSalary: 72000,
      salaryHistory: [
        { from: "2022-04", to: "2023-03", salary: 50000 },
        { from: "2023-04", to: "Present", salary: 72000, isActive: true },
      ],
    },
    {
      id: 3,
      employeeId: "EMP-003",
      name: "Amit Verma",
      department: "Electrical",
      designation: "Electrical Engineer",
      currentSalary: 68000,
      salaryHistory: [
        { from: "2022-01", to: "2022-12", salary: 42000 },
        { from: "2023-01", to: "2023-12", salary: 58000 },
        { from: "2024-01", to: "Present", salary: 68000, isActive: true },
      ],
    },
    {
      id: 4,
      employeeId: "EMP-004",
      name: "Sandeep Singh",
      department: "Fire Fighting",
      designation: "Fire Safety Engineer",
      currentSalary: 60000,
      salaryHistory: [
        { from: "2023-01", to: "Present", salary: 60000, isActive: true },
      ],
    },
  ],
  meta: {
    total: 4,
    currency: "INR",
  },
};
