export const employeeListResponse = {
  data: [
    {
      empId: 'UUID-001',
      employeeId: 'EMP-001',

      firstName: 'Ajay',
      lastName: 'Shakya',
      fullName: 'Ajay new',
      fatherName: 'Ramesh Shakya',
      dob: '1998-05-12',
      gender: 'male',
      mobile: '9876543210',
      email: 'ajay@elmechindia.com',
      aadharNumber: '123412341234',

      joiningDate: '2023-01-10',
      workingStatus: 'working',
      lastWorkingDate: null,
      department: 'IT',
      designation: 'Software Engineer',
      workLocation: 'office',

      tempAddress: 'Indore, Madhya Pradesh',
      permanentAddress: 'Gwalior, Madhya Pradesh',
      role: 'Admin',
      bankName: 'State Bank of India',
      accountNumber: '123456789012',
      ifscCode: 'SBIN0001234',
      salary: 65000,
      salaryHistory: [
        { from: '2023-01', to: '2023-06', salary: 45000 },
        { from: '2023-07', to: '2024-02', salary: 55000 },
        { from: '2024-03', to: 'Present', salary: 65000, isActive: true },
      ],

      emergencyContact: '9876500001',
      emergencyDetails: 'Father',

      document: [],
    },

    {
      empId: 'UUID-002',
      employeeId: 'EMP-002',

      firstName: 'Rohit',
      lastName: 'Mehra',
      fullName: 'Ajay new',
      fatherName: 'Suresh Mehra',
      dob: '1995-08-21',
      gender: 'male',
      mobile: '9123456789',
      email: 'rohit@elmechindia.com',
      aadharNumber: '234523452345',
      role: 'user',

      joiningDate: '2022-11-15',
      workingStatus: 'notice_period',
      lastWorkingDate: null,
      department: 'Civil',
      designation: 'Civil Engineer',
      workLocation: 'site',

      tempAddress: 'Bhopal, Madhya Pradesh',
      permanentAddress: 'Jabalpur, Madhya Pradesh',

      bankName: 'HDFC Bank',
      accountNumber: '456789012345',
      ifscCode: 'HDFC0002345',
      salary: 58000,
      salaryHistory: [
        { from: '2022-11', to: '2023-06', salary: 48000 },
        { from: '2023-07', to: 'Present', salary: 58000, isActive: true },
      ],

      emergencyContact: '9123400011',
      emergencyDetails: 'Brother',

      document: [],
    },

    {
      role: 'employee',

      empId: 'UUID-003',
      employeeId: 'EMP-003',
      firstName: 'Amit',
      lastName: 'Verma',
      fatherName: 'Mahesh Verma',
      dob: '1994-03-10',
      gender: 'male',
      mobile: '9988776655',
      email: 'amit@elmechindia.com',
      aadharNumber: '345634563456',
      fullName: 'Ajay new',
      joiningDate: '2021-06-20',
      workingStatus: 'resigned',
      lastWorkingDate: null,
      department: 'Electrical',
      designation: 'Electrical Engineer',
      workLocation: 'site',

      tempAddress: 'Noida, UP',
      permanentAddress: 'Kanpur, UP',

      bankName: 'ICICI Bank',
      accountNumber: '567890123456',
      ifscCode: 'ICIC0003456',
      salary: 60000,
      salaryHistory: [
        { from: '2021-06', to: '2022-12', salary: 48000 },
        { from: '2023-01', to: 'Present', salary: 60000, isActive: true },
      ],

      emergencyContact: '9988700011',
      emergencyDetails: 'Wife',

      document: [],
    },

    {
      empId: 'UUID-004',
      employeeId: 'EMP-004',
      firstName: 'Neha',
      lastName: 'Sharma',
      fatherName: 'Rakesh Sharma',
      dob: '1997-01-05',
      gender: 'female',
      mobile: '9090909090',
      email: 'neha@elmechindia.com',
      aadharNumber: '456745674567',
      fullName: 'Ajay new',
      joiningDate: '2023-03-01',
      workingStatus: 'terminated',
      lastWorkingDate: null,
      department: 'HR',
      designation: 'HR Executive',
      workLocation: 'office',
      role: 'cfo',
      tempAddress: 'Delhi',
      permanentAddress: 'Jaipur, Rajasthan',

      bankName: 'Axis Bank',
      accountNumber: '678901234567',
      ifscCode: 'UTIB0004567',
      salary: 42000,
      salaryHistory: [{ from: '2023-03', to: 'Present', salary: 42000, isActive: true }],

      emergencyContact: '9090900011',
      emergencyDetails: 'Mother',

      document: [],
    },

    {
      empId: 'UUID-005',
      employeeId: 'EMP-005',
      firstName: 'Vikas',
      lastName: 'Yadav',
      fatherName: 'Rajendra Yadav',
      dob: '1992-11-11',
      gender: 'male',
      mobile: '9811223344',
      email: 'vikas@elmechindia.com',
      aadharNumber: '567856785678',
      fullName: 'Ajay new',
      joiningDate: '2020-08-18',
      workingStatus: 'retired',
      lastWorkingDate: null,
      department: 'Site',
      designation: 'Site Supervisor',
      workLocation: 'site',
      role: 'cto',
      tempAddress: 'Gurgaon, Haryana',
      permanentAddress: 'Rewari, Haryana',

      bankName: 'Punjab National Bank',
      accountNumber: '789012345678',
      ifscCode: 'PUNB0005678',
      salary: 50000,
      salaryHistory: [
        { from: '2020-08', to: '2022-12', salary: 40000 },
        { from: '2023-01', to: 'Present', salary: 50000, isActive: true },
      ],

      emergencyContact: '9811200011',
      emergencyDetails: 'Wife',

      document: [],
    },

    {
      empId: 'UUID-006',
      fullName: 'Ajay new',
      employeeId: 'EMP-006',
      firstName: 'Pankaj',
      lastName: 'Kumar',
      fatherName: 'Shiv Kumar',
      dob: '1991-04-18',
      gender: 'male',
      mobile: '9822334455',
      email: 'pankaj@elmechindia.com',
      aadharNumber: '678967896789',
      role: 'ceo',
      joiningDate: '2019-07-10',
      workingStatus: 'Retired',
      lastWorkingDate: null,
      department: 'Management',
      designation: 'Project Manager',
      workLocation: 'site',

      tempAddress: 'Noida, UP',
      permanentAddress: 'Patna, Bihar',

      bankName: 'HDFC Bank',
      accountNumber: '890123456789',
      ifscCode: 'HDFC0006789',
      salary: 85000,
      salaryHistory: [
        { from: '2019-07', to: '2021-12', salary: 65000 },
        { from: '2022-01', to: 'Present', salary: 85000, isActive: true },
      ],

      emergencyContact: '9822300011',
      emergencyDetails: 'Wife',

      document: [],
    },

    {
      empId: 'UUID-007',
      fullName: 'Ajay new',
      employeeId: 'EMP-007',
      firstName: 'Sunita',
      lastName: 'Gupta',
      fatherName: 'Mohan Gupta',
      dob: '1989-09-02',
      gender: 'female',
      mobile: '9877001122',
      email: 'sunita@elmechindia.com',
      aadharNumber: '789078907890',
      role: 'Project Manager',
      joiningDate: '2018-03-14',
      workingStatus: 'resigned',
      lastWorkingDate: null,
      department: 'Accounts',
      designation: 'Accounts Manager',
      workLocation: 'office',

      tempAddress: 'Indore, MP',
      permanentAddress: 'Ujjain, MP',

      bankName: 'ICICI Bank',
      accountNumber: '901234567890',
      ifscCode: 'ICIC0007890',
      salary: 72000,
      salaryHistory: [
        { from: '2018-03', to: '2020-12', salary: 52000 },
        { from: '2021-01', to: 'Present', salary: 72000, isActive: true },
      ],

      emergencyContact: '9877000011',
      emergencyDetails: 'Husband',

      document: [],
    },

    {
      empId: 'UUID-008',
      employeeId: 'EMP-008',
      firstName: 'Ravi',
      fullName: 'Ajay new',
      lastName: 'Chauhan',
      fatherName: 'Narayan Chauhan',
      dob: '1993-06-27',
      gender: 'male',
      mobile: '9898989898',
      email: 'ravi@elmechindia.com',
      aadharNumber: '890189018901',
      role: 'Finance Manager',
      joiningDate: '2020-10-05',
      workingStatus: 'terminated',
      lastWorkingDate: null,
      department: 'Mechanical',
      designation: 'Mechanical Engineer',
      workLocation: 'site',

      tempAddress: 'Ahmedabad, Gujarat',
      permanentAddress: 'Rajkot, Gujarat',

      bankName: 'Axis Bank',
      accountNumber: '012345678901',
      ifscCode: 'UTIB0008901',
      salary: 62000,
      salaryHistory: [
        { from: '2020-10', to: '2022-06', salary: 48000 },
        { from: '2022-07', to: 'Present', salary: 62000, isActive: true },
      ],

      emergencyContact: '9898900011',
      emergencyDetails: 'Father',

      document: [],
    },

    {
      empId: 'UUID-009',
      employeeId: 'EMP-009',
      firstName: 'Deepak',
      lastName: 'Mishra',
      fullName: 'Ajay new',
      fatherName: 'Sanjay Mishra',
      dob: '1988-12-14',
      gender: 'male',
      mobile: '9700011122',
      email: 'deepak@elmechindia.com',
      aadharNumber: '901290129012',
      role: 'admin',
      joiningDate: '2017-01-20',
      workingStatus: 'resigned',
      lastWorkingDate: '2024-01-31',
      department: 'Store',
      designation: 'Store Manager',
      workLocation: 'site',

      tempAddress: 'Nagpur, Maharashtra',
      permanentAddress: 'Rewa, MP',

      bankName: 'SBI',
      accountNumber: '123450987654',
      ifscCode: 'SBIN0009012',
      salary: 48000,
      salaryHistory: [
        { from: '2017-01', to: '2021-12', salary: 38000 },
        { from: '2022-01', to: '2024-01', salary: 48000 },
      ],

      emergencyContact: '9700000011',
      emergencyDetails: 'Brother',

      document: [],
    },

    {
      empId: 'UUID-010',
      employeeId: 'EMP-010',
      firstName: 'Manish',
      lastName: 'Tiwari',
      fullName: 'Ajay new',
      fatherName: 'Anil Tiwari',
      dob: '1990-07-09',
      gender: 'male',
      mobile: '9998887776',
      email: 'manish@elmechindia.com',
      aadharNumber: '012301230123',

      joiningDate: '2019-09-11',
      workingStatus: 'working',
      lastWorkingDate: null,
      department: 'Safety',
      designation: 'Safety Officer',
      workLocation: 'site',
      role: 'ceo',
      tempAddress: 'Raipur, CG',
      permanentAddress: 'Bilaspur, CG',

      bankName: 'PNB',
      accountNumber: '234561234561',
      ifscCode: 'PUNB0012301',
      salary: 55000,
      salaryHistory: [
        { from: '2019-09', to: '2022-12', salary: 42000 },
        { from: '2023-01', to: 'Present', salary: 55000, isActive: true },
      ],

      emergencyContact: '9998800011',
      emergencyDetails: 'Wife',

      document: [],
    },

    {
      empId: 'UUID-011',
      employeeId: 'EMP-011',
      firstName: 'Anjali',
      lastName: 'Jain',
      fullName: 'Ajay new',
      fatherName: 'Prakash Jain',
      dob: '1996-02-22',
      gender: 'female',
      mobile: '9112233445',
      email: 'anjali@elmechindia.com',
      aadharNumber: '123412341235',

      joiningDate: '2022-05-01',
      workingStatus: 'working',
      lastWorkingDate: null,
      department: 'Design',
      designation: 'Architect',
      workLocation: 'office',

      tempAddress: 'Indore, MP',
      permanentAddress: 'Ratlam, MP',

      bankName: 'Axis Bank',
      accountNumber: '345612345612',
      ifscCode: 'UTIB0012345',
      salary: 70000,
      salaryHistory: [{ from: '2022-05', to: 'Present', salary: 70000, isActive: true }],

      emergencyContact: '9112200011',
      emergencyDetails: 'Father',

      document: [],
    },

    {
      empId: 'UUID-012',
      employeeId: 'EMP-012',
      firstName: 'Kunal',
      lastName: 'Saxena',
      fullName: 'Ajay new',
      fatherName: 'Rajeev Saxena',
      dob: '1992-10-30',
      gender: 'male',
      mobile: '9333444555',
      email: 'kunal@elmechindia.com',
      aadharNumber: '234523452346',

      joiningDate: '2021-02-17',
      workingStatus: 'working',
      lastWorkingDate: null,
      department: 'Planning',
      designation: 'Planning Engineer',
      workLocation: 'office',

      tempAddress: 'Lucknow, UP',
      permanentAddress: 'Bareilly, UP',

      bankName: 'ICICI Bank',
      accountNumber: '456734567345',
      ifscCode: 'ICIC0023456',
      salary: 63000,
      salaryHistory: [
        { from: '2021-02', to: '2022-12', salary: 48000 },
        { from: '2023-01', to: 'Present', salary: 63000, isActive: true },
      ],

      emergencyContact: '9333400011',
      emergencyDetails: 'Mother',

      document: [],
    },

    {
      empId: 'UUID-013',
      employeeId: 'EMP-013',
      firstName: 'Rahul',
      lastName: 'Malhotra',
      fullName: 'Ajay new',
      fatherName: 'Vijay Malhotra',
      dob: '1987-08-19',
      gender: 'male',
      mobile: '9444555666',
      email: 'rahul@elmechindia.com',
      aadharNumber: '345634563457',

      joiningDate: '2016-11-03',
      workingStatus: 'terminated',
      lastWorkingDate: '2023-12-15',
      department: 'Quality',
      designation: 'QA/QC Engineer',
      workLocation: 'site',

      tempAddress: 'Faridabad, Haryana',
      permanentAddress: 'Panipat, Haryana',

      bankName: 'SBI',
      accountNumber: '567845678456',
      ifscCode: 'SBIN0034567',
      salary: 58000,
      salaryHistory: [
        { from: '2016-11', to: '2020-12', salary: 45000 },
        { from: '2021-01', to: '2023-12', salary: 58000 },
      ],

      emergencyContact: '9444500011',
      emergencyDetails: 'Wife',

      document: [],
    },
  ],

  meta: [
    {
      total: 21,
      page: 1,
      limit: 10,
      hasNextPage: true,
    },
  ],
};

export const salaryManagementResponse = {
  data: [
    {
      id: 1,
      employeeId: 'EMP-001',
      name: 'Ajay Shakya',
      department: 'IT',
      designation: 'Software Engineer',
      currentSalary: 65000,
      salaryHistory: [
        { from: '2023-01', to: '2023-06', salary: 45000 },
        { from: '2023-07', to: '2024-02', salary: 55000 },
        { from: '2024-03', to: 'Present', salary: 65000, isActive: true },
      ],
    },
    {
      id: 2,
      employeeId: 'EMP-002',
      name: 'Rohit Mehra',
      department: 'Civil',
      designation: 'Civil Engineer',
      currentSalary: 72000,
      salaryHistory: [
        { from: '2022-04', to: '2023-03', salary: 50000 },
        { from: '2023-04', to: 'Present', salary: 72000, isActive: true },
      ],
    },
    {
      id: 3,
      employeeId: 'EMP-003',
      name: 'Amit Verma',
      department: 'Electrical',
      designation: 'Electrical Engineer',
      currentSalary: 68000,
      salaryHistory: [
        { from: '2022-01', to: '2022-12', salary: 42000 },
        { from: '2023-01', to: '2023-12', salary: 58000 },
        { from: '2024-01', to: 'Present', salary: 68000, isActive: true },
      ],
    },
    {
      id: 4,
      employeeId: 'EMP-004',
      name: 'Sandeep Singh',
      department: 'Fire Fighting',
      designation: 'Fire Safety Engineer',
      currentSalary: 60000,
      salaryHistory: [{ from: '2023-01', to: 'Present', salary: 60000, isActive: true }],
    },
  ],
  meta: {
    total: 4,
    currency: 'INR',
  },
};

export const queryListResponse = {
  data: [
    {
      id: 'QRY-001',
      userId: 'USR-101',
      userName: 'Ajay Shakya',
      email: 'ajay@example.com',
      subject: 'Login issue',
      description: 'Unable to login after password reset',
      priority: 'high',
      status: 'pending',
      createdAt: '2024-12-01',
    },
    {
      id: 'QRY-002',
      userId: 'USR-102',
      userName: 'Rohit Mehra',
      email: 'rohit@example.com',
      subject: 'Salary slip not generated',
      description: 'Salary slip for November is missing',
      priority: 'medium',
      status: 'resolved',
      createdAt: '2024-12-03',
    },
    {
      id: 'QRY-003',
      userId: 'USR-103',
      userName: 'Amit Verma',
      email: 'amit@example.com',
      subject: 'Project access',
      description: 'Unable to access assigned project',
      priority: 'high',
      status: 'pending',
      createdAt: '2024-12-05',
    },
    {
      id: 'QRY-004',
      userId: 'USR-104',
      userName: 'Neha Sharma',
      email: 'neha@example.com',
      subject: 'Profile update issue',
      description: 'Changes not saving in profile',
      priority: 'low',
      status: 'resolved',
      createdAt: '2024-12-06',
    },
    {
      id: 'QRY-005',
      userId: 'USR-105',
      userName: 'Sandeep Singh',
      email: 'sandeep@example.com',
      subject: 'Site allocation',
      description: 'Site location not updated',
      priority: 'medium',
      status: 'pending',
      createdAt: '2024-12-08',
    },
  ],
  meta: {
    total: 5,
    openQueries: 3,
    resolvedQueries: 2,
  },
};

export const commentListResponse = {
  data: [
    {
      id: 'CMT-001',
      userId: 'USR-101',
      userName: 'Ajay Shakya',
      comment: 'The new dashboard UI looks very clean and modern.',
      rating: 5,
      showOnUi: true,
      createdAt: '2024-12-02',
    },
    {
      id: 'CMT-002',
      userId: 'USR-102',
      userName: 'Rohit Mehra',
      comment: 'Salary management feature is very helpful.',
      rating: 4,
      showOnUi: true,
      createdAt: '2024-12-04',
    },
    {
      id: 'CMT-003',
      userId: 'USR-103',
      userName: 'Amit Verma',
      comment: 'Employee filter could be faster.',
      rating: 3,
      showOnUi: false,
      createdAt: '2024-12-05',
    },
    {
      id: 'CMT-004',
      userId: 'USR-104',
      userName: 'Neha Sharma',
      comment: 'Project module is very easy to use.',
      rating: 5,
      showOnUi: true,
      createdAt: '2024-12-07',
    },
    {
      id: 'CMT-005',
      userId: 'USR-105',
      userName: 'Sandeep Singh',
      comment: 'Need dark mode support.',
      rating: 4,
      showOnUi: false,
      createdAt: '2024-12-09',
    },
  ],
  meta: {
    total: 5,
    approved: 3,
    pending: 2,
  },
};

export const allUsersResponse = {
  data: [
    {
      id: 1,
      employeeId: 'EMP-001',
      name: 'Ajay Shakya',
      role: 'Admin',
      department: 'IT',
      status: 'active',
    },
    {
      id: 2,
      employeeId: 'EMP-002',
      name: 'Rohit Mehra',
      role: 'Employee',
      department: 'Civil',
      status: 'active',
    },
    {
      id: 3,
      employeeId: 'EMP-003',
      name: 'Amit Verma',
      role: 'Employee',
      department: 'Electrical',
      status: 'inactive',
    },
  ],
  meta: {
    total: 3,
  },
};
export const allProjectsResponse = {
  data: [
    {
      projectId: 'prj_987654321',
      projectName: 'Commercial Complex Bangalore',
      projectLeadName: 'John Doe',
      projectLeadEmpId: 'EMP001',
      projectCoLeadName: 'Sarah Williams',
      projectCoLeadEmpId: 'EMP005',
      clientType: 'company',
      clientCompany: 'Prestige Constructions Pvt Ltd',
      clientName: 'Rajesh Kumar',
      clientMobile: 9876543210,
      clientEmail: 'rajesh.kumar@prestigeconstructions.com',
      clientAddress: 'MG Road, Bangalore, Karnataka - 560001',
      clientGSTIN: '29AABCP1234F1Z5',
      services: ['civil_construction', 'electrical_works', 'plumbing'],
      projectType: 'commercial',
      projectAddress: 'Whitefield, Bangalore, Karnataka - 560066',
      description: 'Commercial complex with retail spaces, offices, and parking facilities',
      budget: 8000000,
      contractValue: 7500000,
      startDate: '2026-03-01',
      endDate: '2027-09-30',
      projectStatus: 'planned',
      priority: 'high',
      showOnUI: true,
      createdAt: '2026-01-15T10:30:00Z',
      updatedAt: '2026-01-15T10:30:00Z',
    },
    {
      projectId: 'prj_123456789',
      projectName: 'Luxury Apartment Complex Mumbai',
      projectLeadName: 'Ajay Shakya',
      projectLeadEmpId: 'EMP014',
      projectCoLeadName: 'Priya Mehta',
      projectCoLeadEmpId: 'EMP018',
      clientType: 'company',
      clientCompany: 'Oberoi Realty Ltd',
      clientName: 'Vikas Oberoi',
      clientMobile: 9823456789,
      clientEmail: 'vikas.oberoi@oberoirealty.com',
      clientAddress: 'Andheri East, Mumbai, Maharashtra - 400069',
      clientGSTIN: '27AABCO5678G1Z8',
      services: ['civil_construction', 'interior_design', 'landscaping'],
      projectType: 'residential',
      projectAddress: 'Bandra West, Mumbai, Maharashtra - 400050',
      description: '18-storey luxury apartment complex with 120 units and premium amenities',
      budget: 15000000,
      contractValue: 14500000,
      startDate: '2025-09-15',
      endDate: '2027-03-31',
      projectStatus: 'active',
      priority: 'critical',
      showOnUI: true,
      createdAt: '2025-09-01T09:00:00Z',
      updatedAt: '2026-01-18T14:20:00Z',
    },
    {
      projectId: 'prj_456789123',
      projectName: 'Metro Station Construction Delhi',
      projectLeadName: 'Rahul Verma',
      projectLeadEmpId: 'EMP032',
      projectCoLeadName: 'Amit Singh',
      projectCoLeadEmpId: 'EMP041',
      clientType: 'company',
      clientCompany: 'Delhi Metro Rail Corporation',
      clientName: 'Dr. Mangu Singh',
      clientMobile: 9811234567,
      clientEmail: 'mangu.singh@dmrc.org',
      clientAddress: 'Metro Bhawan, Barakhamba Road, New Delhi - 110001',
      clientGSTIN: '07AABCD1234E1Z9',
      services: ['civil_construction', 'electrical_works', 'structural_engineering'],
      projectType: 'infrastructure',
      projectAddress: 'Dwarka Sector 21, New Delhi - 110075',
      description: 'Underground metro station with connecting tunnels and entrance plazas',
      budget: 25000000,
      contractValue: 24000000,
      startDate: '2024-06-01',
      endDate: '2026-05-31',
      projectStatus: 'active',
      priority: 'critical',
      showOnUI: true,
      createdAt: '2024-05-10T11:15:00Z',
      updatedAt: '2026-01-17T16:45:00Z',
    },
    {
      projectId: 'prj_789123456',
      projectName: 'Industrial Warehouse Pune',
      projectLeadName: 'Suresh Patel',
      projectLeadEmpId: 'EMP007',
      projectCoLeadName: 'Kavita Deshmukh',
      projectCoLeadEmpId: 'EMP022',
      clientType: 'company',
      clientCompany: 'Mahindra Logistics Ltd',
      clientName: 'Rampravesh Tiwari',
      clientMobile: 9765432109,
      clientEmail: 'rampravesh.t@mahindralogistics.com',
      clientAddress: 'Hinjewadi, Pune, Maharashtra - 411057',
      clientGSTIN: '27AABCM6789H1Z2',
      services: ['civil_construction', 'electrical_works'],
      projectType: 'industrial',
      projectAddress: 'Chakan, Pune, Maharashtra - 410501',
      description: 'Large-scale warehouse facility with automated storage systems',
      budget: 12000000,
      contractValue: 11500000,
      startDate: '2025-11-01',
      endDate: '2026-08-31',
      projectStatus: 'active',
      priority: 'high',
      showOnUI: true,
      createdAt: '2025-10-15T13:30:00Z',
      updatedAt: '2026-01-18T10:15:00Z',
    },
    {
      projectId: 'prj_321654987',
      projectName: 'Villa Community Hyderabad',
      projectLeadName: 'Lakshmi Nair',
      projectLeadEmpId: 'EMP009',
      projectCoLeadName: 'Karthik Reddy',
      projectCoLeadEmpId: 'EMP028',
      clientType: 'individual',
      clientCompany: null,
      clientName: 'Srinivas Reddy',
      clientMobile: 9440123456,
      clientEmail: 'srinivas.reddy@gmail.com',
      clientAddress: 'Jubilee Hills, Hyderabad, Telangana - 500033',
      clientGSTIN: null,
      services: ['civil_construction', 'interior_design', 'landscaping', 'swimming_pool'],
      projectType: 'residential',
      projectAddress: 'Kokapet, Hyderabad, Telangana - 500075',
      description: 'Gated community with 25 luxury villas, clubhouse, and recreational facilities',
      budget: 18000000,
      contractValue: 17000000,
      startDate: '2026-02-01',
      endDate: '2027-08-31',
      projectStatus: 'planned',
      priority: 'medium',
      showOnUI: true,
      createdAt: '2026-01-10T08:45:00Z',
      updatedAt: '2026-01-10T08:45:00Z',
    },
    {
      projectId: 'prj_654987321',
      projectName: 'Hospital Expansion Chennai',
      projectLeadName: 'Dr. Anil Kumar',
      projectLeadEmpId: 'EMP012',
      projectCoLeadName: 'Sangeeta Iyer',
      projectCoLeadEmpId: 'EMP035',
      clientType: 'company',
      clientCompany: 'Apollo Hospitals Enterprise Ltd',
      clientName: 'Dr. Prathap C Reddy',
      clientMobile: 9841234567,
      clientEmail: 'prathap.reddy@apollohospitals.com',
      clientAddress: 'Greams Road, Chennai, Tamil Nadu - 600006',
      clientGSTIN: '33AABCA7890I1Z3',
      services: ['civil_construction', 'electrical_works', 'plumbing', 'hvac'],
      projectType: 'commercial',
      projectAddress: 'OMR, Chennai, Tamil Nadu - 600097',
      description:
        'New wing addition with 200 beds, ICU, operation theaters, and diagnostic center',
      budget: 20000000,
      contractValue: 19000000,
      startDate: '2025-05-01',
      endDate: '2026-10-31',
      projectStatus: 'active',
      priority: 'critical',
      showOnUI: true,
      createdAt: '2025-04-15T10:00:00Z',
      updatedAt: '2026-01-18T12:30:00Z',
    },
    {
      projectId: 'prj_147258369',
      projectName: 'Shopping Mall Jaipur',
      projectLeadName: 'Manish Sharma',
      projectLeadEmpId: 'EMP015',
      projectCoLeadName: 'Neha Gupta',
      projectCoLeadEmpId: 'EMP042',
      clientType: 'company',
      clientCompany: 'DLF Limited',
      clientName: 'Rajiv Singh',
      clientMobile: 9414567890,
      clientEmail: 'rajiv.singh@dlf.in',
      clientAddress: 'C-Scheme, Jaipur, Rajasthan - 302001',
      clientGSTIN: '08AABCD2345F1Z4',
      services: ['civil_construction', 'electrical_works', 'interior_design', 'fire_safety'],
      projectType: 'commercial',
      projectAddress: 'Vaishali Nagar, Jaipur, Rajasthan - 302021',
      description: '4-level shopping mall with multiplex, food court, and entertainment zone',
      budget: 22000000,
      contractValue: 21000000,
      startDate: '2024-08-01',
      endDate: '2026-06-30',
      projectStatus: 'active',
      priority: 'high',
      showOnUI: true,
      createdAt: '2024-07-20T14:00:00Z',
      updatedAt: '2026-01-18T09:20:00Z',
    },
    {
      projectId: 'prj_963852741',
      projectName: 'IT Campus Kolkata',
      projectLeadName: 'Soumya Banerjee',
      projectLeadEmpId: 'EMP020',
      projectCoLeadName: 'Debashis Roy',
      projectCoLeadEmpId: 'EMP038',
      clientType: 'company',
      clientCompany: 'Tata Consultancy Services',
      clientName: 'Rajesh Gopinathan',
      clientMobile: 9830123456,
      clientEmail: 'rajesh.gopinathan@tcs.com',
      clientAddress: 'Salt Lake, Kolkata, West Bengal - 700091',
      clientGSTIN: '19AABCT3456J1Z5',
      services: ['civil_construction', 'electrical_works', 'network_infrastructure', 'hvac'],
      projectType: 'commercial',
      projectAddress: 'New Town, Kolkata, West Bengal - 700156',
      description:
        'Modern IT campus with office towers, cafeteria, and recreational facilities for 5000 employees',
      budget: 30000000,
      contractValue: 28500000,
      startDate: '2025-01-15',
      endDate: '2027-01-15',
      projectStatus: 'active',
      priority: 'critical',
      showOnUI: true,
      createdAt: '2024-12-01T11:30:00Z',
      updatedAt: '2026-01-18T15:10:00Z',
    },
    {
      projectId: 'prj_258369147',
      projectName: 'Highway Bridge Construction',
      projectLeadName: 'Vikram Chauhan',
      projectLeadEmpId: 'EMP025',
      projectCoLeadName: 'Anjali Thakur',
      projectCoLeadEmpId: 'EMP049',
      clientType: 'company',
      clientCompany: 'National Highways Authority of India',
      clientName: 'Alka Upadhyaya',
      clientMobile: 9717890123,
      clientEmail: 'alka.upadhyaya@nhai.gov.in',
      clientAddress: 'G-5&6, Sector-10, Dwarka, New Delhi - 110075',
      clientGSTIN: '07AABCN4567K1Z6',
      services: ['civil_construction', 'structural_engineering'],
      projectType: 'infrastructure',
      projectAddress: 'NH-44, Ambala-Chandigarh Highway - 134003',
      description: 'Six-lane elevated highway bridge spanning 2.5 km with modern safety features',
      budget: 35000000,
      contractValue: 33000000,
      startDate: '2023-10-01',
      endDate: '2025-12-31',
      projectStatus: 'completed',
      priority: 'critical',
      showOnUI: true,
      createdAt: '2023-09-15T09:00:00Z',
      updatedAt: '2026-01-05T16:00:00Z',
    },
    {
      projectId: 'prj_741852963',
      projectName: 'Resort Development Goa',
      projectLeadName: "Maria D'Souza",
      projectLeadEmpId: 'EMP030',
      projectCoLeadName: 'Rohan Fernandes',
      projectCoLeadEmpId: 'EMP052',
      clientType: 'individual',
      clientCompany: null,
      clientName: 'Antonio Fernandes',
      clientMobile: 9823334455,
      clientEmail: 'antonio.fernandes@gmail.com',
      clientAddress: 'Panjim, Goa - 403001',
      clientGSTIN: null,
      services: [
        'civil_construction',
        'interior_design',
        'landscaping',
        'swimming_pool',
        'electrical_works',
      ],
      projectType: 'commercial',
      projectAddress: 'Candolim Beach Road, Goa - 403515',
      description: 'Boutique beach resort with 50 rooms, spa, restaurant, and beachfront amenities',
      budget: 16000000,
      contractValue: 15200000,
      startDate: '2026-04-01',
      endDate: '2027-11-30',
      projectStatus: 'planned',
      priority: 'medium',
      showOnUI: true,
      createdAt: '2026-01-12T12:00:00Z',
      updatedAt: '2026-01-12T12:00:00Z',
    },
  ],
  meta: {
    total: 10,
  },
};

// Dummy Requirements Response Data
export const dummyRequirementsData = {
  data: [
    {
      reqId: 'REQ_001',
      path: '/dashboard',
      requirementType: 'bug_fix',
      description:
        'Dashboard widgets are not loading properly on page refresh. Need to fix the data fetching logic.',
      status: 'in_progress',
      openedAt: '2026-01-10T09:30:00Z',
      closedAt: null,
      developerThought:
        'Working on fixing the async data loading issue. Should be resolved by end of week.',
      employeeName: 'Ajay Shakya',
      employeeId: 'EMP001',
      createdAt: '2026-01-10T09:30:00Z',
      updatedAt: '2026-01-15T14:20:00Z',
    },
    {
      reqId: 'REQ_002',
      path: '/salary-management',
      requirementType: 'new_feature',
      description:
        'Need to add bulk salary update feature for HR department. Should support Excel upload.',
      status: 'submitted',
      openedAt: '2026-01-12T11:45:00Z',
      closedAt: null,
      developerThought: null,
      employeeName: 'Rohit Verma',
      employeeId: 'EMP002',
      createdAt: '2026-01-12T11:45:00Z',
      updatedAt: '2026-01-12T11:45:00Z',
    },
    {
      reqId: 'REQ_003',
      path: '/employee/attendance',
      requirementType: 'ui_ux_improvement',
      description:
        'The attendance calendar is too small and hard to read. Please make it bigger and more user-friendly.',
      status: 'completed',
      openedAt: '2025-12-28T10:15:00Z',
      closedAt: '2026-01-08T16:30:00Z',
      developerThought:
        'Implemented improved calendar with better date picker and visual indicators.',
      employeeName: 'Neha Singh',
      employeeId: 'EMP003',
      createdAt: '2025-12-28T10:15:00Z',
      updatedAt: '2026-01-08T16:30:00Z',
    },
    {
      reqId: 'REQ_004',
      path: '/projects/list',
      requirementType: 'performance_issue',
      description:
        'Project list page is very slow when we have more than 100 projects. Takes 10+ seconds to load.',
      status: 'under_review',
      openedAt: '2026-01-14T08:20:00Z',
      closedAt: null,
      developerThought:
        'Need to implement pagination and lazy loading. Reviewing the current implementation.',
      employeeName: 'Suresh Patel',
      employeeId: 'EMP007',
      createdAt: '2026-01-14T08:20:00Z',
      updatedAt: '2026-01-16T10:00:00Z',
    },
    {
      reqId: 'REQ_005',
      path: '/reports/monthly',
      requirementType: 'data_issue',
      description:
        "Monthly report is showing incorrect total values. The sum doesn't match individual entries.",
      status: 'in_progress',
      openedAt: '2026-01-11T13:40:00Z',
      closedAt: null,
      developerThought: 'Found the issue in the aggregation query. Fixing the calculation logic.',
      employeeName: 'Lakshmi Nair',
      employeeId: 'EMP009',
      createdAt: '2026-01-11T13:40:00Z',
      updatedAt: '2026-01-17T11:25:00Z',
    },
    {
      reqId: 'REQ_006',
      path: '/inventory/stock',
      requirementType: 'navigation_issue',
      description:
        "After adding new stock item, the page doesn't redirect properly. Gets stuck on the form page.",
      status: 'completed',
      openedAt: '2026-01-05T15:10:00Z',
      closedAt: '2026-01-09T12:00:00Z',
      developerThought:
        'Fixed the navigation flow. Now properly redirects to stock list after successful addition.',
      employeeName: 'Dr. Anil Kumar',
      employeeId: 'EMP012',
      createdAt: '2026-01-05T15:10:00Z',
      updatedAt: '2026-01-09T12:00:00Z',
    },
    {
      reqId: 'REQ_007',
      path: '/employee/profile',
      requirementType: 'form_validation',
      description:
        'Employee profile form allows saving without mandatory fields. Need proper validation.',
      status: 'rejected',
      openedAt: '2026-01-13T09:00:00Z',
      closedAt: '2026-01-14T10:30:00Z',
      developerThought:
        'This is already implemented. Please check the required fields marked with asterisk (*). Closing this request.',
      employeeName: 'Manish Sharma',
      employeeId: 'EMP015',
      createdAt: '2026-01-13T09:00:00Z',
      updatedAt: '2026-01-14T10:30:00Z',
    },
    {
      reqId: 'REQ_008',
      path: '/clients/invoices',
      requirementType: 'export_import',
      description: 'Need to export invoices to PDF with company logo and proper formatting.',
      status: 'submitted',
      openedAt: '2026-01-15T14:30:00Z',
      closedAt: null,
      developerThought: null,
      employeeName: 'Soumya Banerjee',
      employeeId: 'EMP020',
      createdAt: '2026-01-15T14:30:00Z',
      updatedAt: '2026-01-15T14:30:00Z',
    },
    {
      reqId: 'REQ_009',
      path: '/dashboard/analytics',
      requirementType: 'report_generation',
      description:
        'Add monthly analytics report with graphs for revenue, expenses, and project completion rate.',
      status: 'under_review',
      openedAt: '2026-01-16T10:45:00Z',
      closedAt: null,
      developerThought:
        'Good suggestion. Will discuss with team and provide estimate by next week.',
      employeeName: 'Vikram Chauhan',
      employeeId: 'EMP025',
      createdAt: '2026-01-16T10:45:00Z',
      updatedAt: '2026-01-17T09:15:00Z',
    },
    {
      reqId: 'REQ_010',
      path: '/settings/users',
      requirementType: 'access_control',
      description:
        "Need role-based access control. Junior employees shouldn't see salary information.",
      status: 'in_progress',
      openedAt: '2026-01-08T11:20:00Z',
      closedAt: null,
      developerThought:
        'Implementing comprehensive RBAC system. This will take 2-3 weeks to complete properly.',
      employeeName: "Maria D'Souza",
      employeeId: 'EMP030',
      createdAt: '2026-01-08T11:20:00Z',
      updatedAt: '2026-01-16T15:40:00Z',
    },
    {
      reqId: 'REQ_011',
      path: '/projects/timeline',
      requirementType: 'responsive_design',
      description:
        "Project timeline doesn't display properly on mobile devices. Need mobile-friendly design.",
      status: 'submitted',
      openedAt: '2026-01-17T08:15:00Z',
      closedAt: null,
      developerThought: null,
      employeeName: 'Ajay Shakya',
      employeeId: 'EMP001',
      createdAt: '2026-01-17T08:15:00Z',
      updatedAt: '2026-01-17T08:15:00Z',
    },
    {
      reqId: 'REQ_012',
      path: '/tasks/board',
      requirementType: 'search_filter',
      description:
        'Task board needs better filtering options - by status, assignee, priority, and date range.',
      status: 'completed',
      openedAt: '2025-12-20T13:30:00Z',
      closedAt: '2026-01-03T17:00:00Z',
      developerThought: 'Implemented advanced filtering with save filter presets feature as well.',
      employeeName: 'Rohit Verma',
      employeeId: 'EMP002',
      createdAt: '2025-12-20T13:30:00Z',
      updatedAt: '2026-01-03T17:00:00Z',
    },
    {
      reqId: 'REQ_013',
      path: '/notifications',
      requirementType: 'notification',
      description:
        'Not receiving notifications for project updates. Need real-time notification system.',
      status: 'on_hold',
      openedAt: '2026-01-09T16:00:00Z',
      closedAt: null,
      developerThought:
        'This requires WebSocket implementation. On hold pending infrastructure upgrade.',
      employeeName: 'Neha Singh',
      employeeId: 'EMP003',
      createdAt: '2026-01-09T16:00:00Z',
      updatedAt: '2026-01-12T10:20:00Z',
    },
    {
      reqId: 'REQ_014',
      path: '/leave/apply',
      requirementType: 'api_integration',
      description: 'Leave application should send email notification to manager automatically.',
      status: 'in_progress',
      openedAt: '2026-01-13T12:10:00Z',
      closedAt: null,
      developerThought: 'Integrating email service. Testing phase currently ongoing.',
      employeeName: 'Suresh Patel',
      employeeId: 'EMP007',
      createdAt: '2026-01-13T12:10:00Z',
      updatedAt: '2026-01-18T08:30:00Z',
    },
    {
      reqId: 'REQ_015',
      path: '/settings/theme',
      requirementType: 'other',
      description:
        'Add dark mode toggle option in settings. Current bright theme causes eye strain.',
      status: 'submitted',
      openedAt: '2026-01-18T07:45:00Z',
      closedAt: null,
      developerThought: null,
      employeeName: 'Lakshmi Nair',
      employeeId: 'EMP009',
      createdAt: '2026-01-18T07:45:00Z',
      updatedAt: '2026-01-18T07:45:00Z',
    },
  ],
  meta: {
    total: 15,
    submitted: 5,
    underReview: 2,
    inProgress: 4,
    completed: 3,
    rejected: 1,
    onHold: 1,
  },
};
