import { MENU_KEYS } from '../constants/menuKeys';

export const USER_ROLES = {
  ADMIN: 'admin',
  MANAGER: 'manager',
  USER: 'user',
  GUEST: 'guest',
};

export const MENU_PERMISSIONS = {
  [MENU_KEYS.DASHBOARD]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],

  // Employee Management
  [MENU_KEYS.EMPLOYEE_MANAGEMENT]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  [MENU_KEYS.ADD_EMPLOYEE]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  [MENU_KEYS.ALL_EMPLOYEES]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],

  // Salary
  [MENU_KEYS.SALARY_MANAGEMENT]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],

  // User Management
  [MENU_KEYS.MY_PROFILE]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],
  [MENU_KEYS.ALL_USERS]: [USER_ROLES.ADMIN],
  [MENU_KEYS.USER_COMMENTS]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  [MENU_KEYS.USER_QUERIES]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],

  // Projects
  [MENU_KEYS.PROJECTS]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  [MENU_KEYS.ADD_PROJECT]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  [MENU_KEYS.ALL_PROJECTS]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],
};

export const hasMenuPermission = (menuKey, userRole) => {
  const allowedRoles = MENU_PERMISSIONS[menuKey];
  return allowedRoles ? allowedRoles.includes(userRole) : false;
};

export default MENU_PERMISSIONS;
