import { MENU_KEYS } from '../constants/menuKeys';

export const USER_ROLES = {
  ADMIN: 'admin',
  MANAGER: 'manager',
  USER: 'user',
  GUEST: 'guest',
};


export const MENU_PERMISSIONS = {
  [MENU_KEYS.DASHBOARD]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],
  [MENU_KEYS.ANALYTICS]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  [MENU_KEYS.USERS]: [USER_ROLES.ADMIN],
  [MENU_KEYS.USER_LIST]: [USER_ROLES.ADMIN],
  [MENU_KEYS.USER_ROLES]: [USER_ROLES.ADMIN],
  [MENU_KEYS.USER_PERMISSIONS]: [USER_ROLES.ADMIN],
  [MENU_KEYS.TEAMS]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  [MENU_KEYS.TEAM_MANAGEMENT]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  [MENU_KEYS.TEAM_ANALYTICS]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  [MENU_KEYS.PROJECTS]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],
  [MENU_KEYS.PROJECT_LIST]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],
  [MENU_KEYS.PROJECT_CREATE]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  [MENU_KEYS.PROJECT_ARCHIVE]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  [MENU_KEYS.SETTINGS]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],
  [MENU_KEYS.GENERAL_SETTINGS]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],
  [MENU_KEYS.SECURITY]: [USER_ROLES.ADMIN],
  [MENU_KEYS.NOTIFICATIONS]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],
  [MENU_KEYS.FILES]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],
  [MENU_KEYS.REPORTS]: [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
};

/**
 * Check if user has permission to access menu item
 * @param {string} menuKey - Menu item key
 * @param {string} userRole - User's role
 * @returns {boolean} True if user has permission
 */
export const hasMenuPermission = (menuKey, userRole) => {
  const allowedRoles = MENU_PERMISSIONS[menuKey];
  return allowedRoles ? allowedRoles.includes(userRole) : false;
};

export default MENU_PERMISSIONS;